#!/bin/bash

./myparser.o <tests/step7-test21.txt >tests/step7-test21mine.txt
./tiny tests/step7-test21mine.txt < tests/step7-test21input.txt
./tiny tests/step7-test21out.txt < tests/step7-test21input.txt
